name: al
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: guruliciousjide@gmail.com <guruliciousjide@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

# dependencies:
#   http: 

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
